### ISSUE TITLE
Blur causes light to bleed through walls

### ISSUE THREAD

**Issue by RulyTafzil** [BlitzKraig/fvtt-DancingLights#6] opened 2020-07-10 19:19 UTC
It seems like the blur effect is causing some light to bleed through walls. 
![image](https://user-images.githubusercontent.com/16487374/87190589-95fe0100-c2a7-11ea-9f1a-365daeecd61e.png)

**Comment by BlitzKraig** [comment] 2020-07-11 18:49
Hey,
Can you send me some more info? I'm not sure what I'm looking at in the screenshot. Is there a light source somewhere in the bottom half of the screenshot that's bleeding through the wall in the middle?

**Comment by BlitzKraig** [comment] 2020-07-12 12:15
Hi RulyTafzil,

I've just checked this, and can reproduce the issue.

I agree that this is unwanted behaviour, however I'm struggling to think up a fix for it.
I'll mull it over a bit, if anyone has any ideas please feel free to post them.

Thanks

**Comment by Princess-Cheeseballs** [comment] 2020-07-23 23:56
I came to report the same issue as well.
I'm making more than a few assumptions about the code when suggesting this solution, so no idea if this helps or not.
I noticed that zooming out causes it to blur more effectively revealing more, which leads me to believe that when blurring it's taking an average of 2 brightness values.
A possible solution could just be that when it encounters a wall, it just duplicates the brightness value.
As an example, lets say you have light source a on the left of a wall and no light source on the right.
If you're checking for blurring on the left and encounter a wall, instead of using the brightness value on the other side, it just uses its own value again, setting the brightness the same across the entire left side of the wall. 
And then on the right side, assuming the brightness is 0 because there is no light, it also assumes the wall has a brightness of 0, so it keeps everything along the wall at 0 for brightness.

Hope this was of some help. If it didn't, some user friendly insight into how the code works might help me rephrase the idea.

**Comment by BlitzKraig** [comment] 2020-07-24 13:20
Hi Pronana,

Unfortunately, we don't have that much control over the brightness as standard.

I'll need to dig into PIXI a bit more, or have a chat with some of the devs who are more familiar with it. I was looking at `filterArea`s, whicih might help, but not sure if I'm on the totally wrong path.

With Foundry 0.7.1, we're expecting big changes to how the lighting system works anyway, so I'll need to prepare for that when the alpha comes out. Maybe I can come up with a solution then.

**Comment by BlitzKraig** [comment] 2020-07-25 13:12
Further note, I'm also considering disabling lights which cannot be seen by a token for performance reasons.

This would probably also sort this issue for the most part as a side effect

**Comment by BlitzKraig** [comment] 2020-08-01 14:05
Thanks to Moerill for the tips on the dev discord, I've found a solution for this.

A fix will be released in 2.1.1, and can be enabled in the module settings - I decided to release it this way as it may need some further testing, though I'm fairly confident it will not cause any problems.

**Comment by BlitzKraig** [comment] 2020-08-01 16:08
Fixed in 2.1.1

**Closed as completed by BlitzKraig** 2020-08-01 16:08 UTC
